In [1]:
import cv2
import numpy as np
import os
os.chdir(r"C:\Users\DT1\Desktop\proj-python\Images_Vision")

In [22]:
img=cv2.imread("logo_opencv.png")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
ret,threshold=cv2.threshold(gray,200,255,cv2.THRESH_BINARY)
contours,hierarchy=cv2.findContours(threshold,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
cv2.drawContours(img,contours,-1,(255,0,0),3)
print(hierarchy)
print(contours)
print(f"number of contours {len(contours)}")
cv2.imshow("Logo",img)
cv2.imshow("Threshold",threshold)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[-1 -1  1 -1]
  [ 5 -1  2  0]
  [ 3 -1 -1  1]
  [ 4  2 -1  1]
  [-1  3 -1  1]
  [ 6  1 -1  0]
  [ 7  5 -1  0]
  [ 8  6 -1  0]
  [ 9  7 -1  0]
  [10  8 -1  0]
  [11  9 -1  0]
  [12 10 -1  0]
  [13 11 -1  0]
  [-1 12 -1  0]]]
(array([[[  0,   0]],

       [[  0, 359]],

       [[511, 359]],

       [[511,   0]]], dtype=int32), array([[[202, 273]],

       [[203, 272]],

       [[211, 272]],

       [[212, 273]],

       [[213, 273]],

       [[214, 274]],

       [[214, 275]],

       [[215, 275]],

       [[216, 276]],

       [[216, 277]],

       [[217, 278]],

       [[217, 279]],

       [[218, 280]],

       [[218, 282]],

       [[221, 279]],

       [[231, 279]],

       [[232, 280]],

       [[233, 280]],

       [[234, 281]],

       [[234, 282]],

       [[235, 282]],

       [[236, 283]],

       [[236, 284]],

       [[237, 285]],

       [[237, 287]],

       [[237, 285]],

       [[238, 284]],

       [[238, 283]],

       [[239, 282]],

       [[240, 282]],

       [[24

# simple project

In [1]:
import cv2
import os
os.chdir(r"C:\Users\DT1\Desktop\proj-python\Images_Vision")

# Read image
img = cv2.imread("logo_eagle.jpg")

# Resize
img = cv2.resize(img, (800, 600))

# Convert to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Threshold
_, binary = cv2.threshold(
    gray,
    127,
    255,
    cv2.THRESH_BINARY
)

# Find contours
contours, hierarchy = cv2.findContours(
    binary,
    cv2.RETR_EXTERNAL,
    cv2.CHAIN_APPROX_SIMPLE
)

print("Number of objects:", len(contours))

# Draw contours
result = img.copy()

cv2.drawContours(
    result,
    contours,
    -1,
    (0, 255, 0),
    2
)

# Put object number on image
for i, contour in enumerate(contours):

    # Calculate center
    M = cv2.moments(contour)

    if M["m00"] != 0:
        cx = int(M["m10"] / M["m00"])
        cy = int(M["m01"] / M["m00"])

        cv2.putText(
            result,
            f"Object {i + 1}",
            (cx - 40, cy),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (0, 0, 255),
            2
        )

# Display
cv2.imshow("Original", img)
cv2.imshow("Binary", binary)
cv2.imshow("Contours", result)

cv2.waitKey(0)
cv2.destroyAllWindows()

Number of objects: 1
