In [1]:
import numpy as np
import cv2
import os
os.chdir(r"D:\proj-python\Images_Vision")

In [26]:

# Checker Board
def save_checker_board(file_name,square_size_cm,num_squares):
    rows=num_squares[0]
    cols=num_squares[1]
    pixel_per_cm=100
    square_size_px=int(square_size_cm*pixel_per_cm)
    board=np.zeros((rows*square_size_px,cols*square_size_px,3),dtype=np.uint8)

    for i in range(rows):
        for j in range(cols):
            if (i+j)%2==0:
                color=(255,255,255)
                # color=(55,255,25)
           
            else:
                color=(0,0,0)
                # color=(55,0,0)


            board[i*square_size_px:(i+1)*square_size_px,j*square_size_px:(j+1)*square_size_px]=color

    cv2.imwrite(file_name,board)
    cv2.imshow("Checker Board",board)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

save_checker_board("checker_board_1.png",1,(8,8))


# **Camera Calibration — Chessboard Corner Detection and Sub-Pixel Refinement** 📷
 

In [2]:
import cv2
import os

chess_board_intersect = (7,7)
chess_board_size = (8,8)
images_chess = "CHESS_IMG"

if not os.path.exists(images_chess):
    os.makedirs(images_chess)
    print("Chess Board Images Folder Created")
else:
    print(f"{images_chess} Folder Already Exists")

criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER,30,0.001)

def detect_checker_board(image,gray_image,criteria,chess_board_intersect,chess_board_size):
    ret,corners = cv2.findChessboardCorners(gray_image,chess_board_intersect,None)

    if ret:
        corners2 = cv2.cornerSubPix(gray_image,corners,(11,11),(-1,-1),criteria)
        image = cv2.drawChessboardCorners(image,chess_board_intersect,corners2,ret)

    return image,ret

cap = cv2.VideoCapture(1)
cap.set(3,1280)
cap.set(4,720)

saved_images = 0

while True:
    ret,frame = cap.read()

    if not ret:
        break

    frame = cv2.rotate(frame,cv2.ROTATE_90_CLOCKWISE)
    gray_frame = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

    result,detected = detect_checker_board(frame,gray_frame,criteria,chess_board_intersect,chess_board_size)

    cv2.putText(frame,f"Saved Images: {saved_images}",(30,50),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)
    cv2.putText(frame,f"Detected: {detected}",(30,100),cv2.FONT_HERSHEY_SIMPLEX,1,(0,255,0),2)

    cv2.imshow("Checker Board",frame)
    cv2.imshow("Checker Board Gray",gray_frame)

    key = cv2.waitKey(1) & 0xFF

    if key == ord("q"):
        break

    elif key == ord("s") and detected:
        saved_images += 1
        filename = f"{images_chess}/image_{saved_images}.jpg"
        cv2.imwrite(filename,frame)
        print(f"Image {saved_images} saved: {filename}")

cap.release()
cv2.destroyAllWindows()

Chess Board Images Folder Created
Image 1 saved: CHESS_IMG/image_1.jpg
Image 2 saved: CHESS_IMG/image_2.jpg
Image 3 saved: CHESS_IMG/image_3.jpg
Image 4 saved: CHESS_IMG/image_4.jpg
Image 5 saved: CHESS_IMG/image_5.jpg
Image 6 saved: CHESS_IMG/image_6.jpg
Image 7 saved: CHESS_IMG/image_7.jpg
Image 8 saved: CHESS_IMG/image_8.jpg
Image 9 saved: CHESS_IMG/image_9.jpg
Image 10 saved: CHESS_IMG/image_10.jpg


In [2]:
obj_3d=np.zeros((7*7,3),dtype=np.float32)
obj_3d[:,:2]=np.mgrid[0:7,0:7].T.reshape(-1,2)
print(obj_3d)
dist=20


[[0. 0. 0.]
 [1. 0. 0.]
 [2. 0. 0.]
 [3. 0. 0.]
 [4. 0. 0.]
 [5. 0. 0.]
 [6. 0. 0.]
 [0. 1. 0.]
 [1. 1. 0.]
 [2. 1. 0.]
 [3. 1. 0.]
 [4. 1. 0.]
 [5. 1. 0.]
 [6. 1. 0.]
 [0. 2. 0.]
 [1. 2. 0.]
 [2. 2. 0.]
 [3. 2. 0.]
 [4. 2. 0.]
 [5. 2. 0.]
 [6. 2. 0.]
 [0. 3. 0.]
 [1. 3. 0.]
 [2. 3. 0.]
 [3. 3. 0.]
 [4. 3. 0.]
 [5. 3. 0.]
 [6. 3. 0.]
 [0. 4. 0.]
 [1. 4. 0.]
 [2. 4. 0.]
 [3. 4. 0.]
 [4. 4. 0.]
 [5. 4. 0.]
 [6. 4. 0.]
 [0. 5. 0.]
 [1. 5. 0.]
 [2. 5. 0.]
 [3. 5. 0.]
 [4. 5. 0.]
 [5. 5. 0.]
 [6. 5. 0.]
 [0. 6. 0.]
 [1. 6. 0.]
 [2. 6. 0.]
 [3. 6. 0.]
 [4. 6. 0.]
 [5. 6. 0.]
 [6. 6. 0.]]


In [3]:
obj_3d*=dist
print(obj_3d)

[[  0.   0.   0.]
 [ 20.   0.   0.]
 [ 40.   0.   0.]
 [ 60.   0.   0.]
 [ 80.   0.   0.]
 [100.   0.   0.]
 [120.   0.   0.]
 [  0.  20.   0.]
 [ 20.  20.   0.]
 [ 40.  20.   0.]
 [ 60.  20.   0.]
 [ 80.  20.   0.]
 [100.  20.   0.]
 [120.  20.   0.]
 [  0.  40.   0.]
 [ 20.  40.   0.]
 [ 40.  40.   0.]
 [ 60.  40.   0.]
 [ 80.  40.   0.]
 [100.  40.   0.]
 [120.  40.   0.]
 [  0.  60.   0.]
 [ 20.  60.   0.]
 [ 40.  60.   0.]
 [ 60.  60.   0.]
 [ 80.  60.   0.]
 [100.  60.   0.]
 [120.  60.   0.]
 [  0.  80.   0.]
 [ 20.  80.   0.]
 [ 40.  80.   0.]
 [ 60.  80.   0.]
 [ 80.  80.   0.]
 [100.  80.   0.]
 [120.  80.   0.]
 [  0. 100.   0.]
 [ 20. 100.   0.]
 [ 40. 100.   0.]
 [ 60. 100.   0.]
 [ 80. 100.   0.]
 [100. 100.   0.]
 [120. 100.   0.]
 [  0. 120.   0.]
 [ 20. 120.   0.]
 [ 40. 120.   0.]
 [ 60. 120.   0.]
 [ 80. 120.   0.]
 [100. 120.   0.]
 [120. 120.   0.]]


In [15]:

chess_dim_size=(7,7)
chess_dim_intersect=(7,7)
square_size=20
criteria=(cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,30,0.001)

folder_calibration="Calibration"

if os.path.exists(folder_calibration):
  print("Folder Of Calibration Found")
else:
  print("Folder Of Calibration Not Found")
  os.makedirs(folder_calibration)
  print("folder_calibration Created")

obj_3d=np.zeros((chess_dim_intersect[0]*chess_dim_intersect[1],3),dtype=np.float32)
obj_3d[:,:2]=np.mgrid[0:chess_dim_intersect[0],0:chess_dim_intersect[1]].T.reshape(-1,2)

dist=20
obj_3d*=dist

obj_points_3d=[]
obj_points_2d=[]

data_path="CHESS_IMG"
folder_img=os.listdir(data_path)

print("Number of images:",len(folder_img))

for img_file in folder_img:
  img=cv2.imread(os.path.join(data_path,img_file))

  if img is None:
    print("Could not read:",img_file)
    continue

  img_gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

  ret,corners=cv2.findChessboardCorners(img_gray,chess_dim_size,None)

  if ret:
    obj_points_3d.append(obj_3d)

    corners2=cv2.cornerSubPix(img_gray,corners,(11,11),(-1,-1),criteria)

    obj_points_2d.append(corners2)

    img=cv2.drawChessboardCorners(img,chess_dim_size,corners2,ret)

    cv2.imshow("Chess Board",img)
    cv2.waitKey(1000)
    # if cv2.waitKey(500)&0xFF==ord("q"):
    #   break

  else:
    print("Chessboard not found:",img_file)

cv2.destroyAllWindows()

print("Successful detections:",len(obj_points_2d))

if len(obj_points_2d)==0:
  print("No chessboard was detected. Calibration cannot be performed.")
else:
  ret,mtx,dist,rvecs,tvecs=cv2.calibrateCamera(obj_points_3d,obj_points_2d,img_gray.shape[::-1],None,None)

  print("Now camera calibrated:")
  print(mtx)

  np.savez(f"{folder_calibration}/Parameters",camMatrix=mtx,distCoef=dist,rVector=rvecs,tVector=tvecs)

  print("Camera parameters saved successfully.")

cv2.destroyAllWindows()


Folder Of Calibration Found
Number of images: 10
Chessboard not found: image_10.jpg
Chessboard not found: image_4.jpg
Chessboard not found: image_7.jpg
Chessboard not found: image_9.jpg
Successful detections: 6
Now camera calibrated:
[[1.59973663e+03 0.00000000e+00 5.39770260e+02]
 [0.00000000e+00 1.56842636e+03 8.89616180e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Camera parameters saved successfully.


# Loading Parameters

In [4]:
print("Loading parameters stored for camera calibration")
folder_calibration="Calibration"
if not os.path.exists(folder_calibration):
    print(f"Folder {folder_calibration} does not exist")
    exit()
params=np.load(f"{folder_calibration}/Parameters.npz")
mtx=params["camMatrix"]
dist=params["distCoef"]
rvecs=params["rVector"]
tvecs=params["tVector"]
print("Parameters Loaded successfully:")
print(mtx)

Loading parameters stored for camera calibration
Parameters Loaded successfully:
[[1.59973663e+03 0.00000000e+00 5.39770260e+02]
 [0.00000000e+00 1.56842636e+03 8.89616180e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [3]:
import numpy as np
import cv2
from enum import Enum
from matplotlib import pyplot as plt
import glob
import os
os.chdir(r"D:\proj-python\Images_Vision")

# How To Use Enum 

In [8]:
from enum import Enum
class color(Enum):
  RED=1
  GREEN=2
  BLUE=3
print("Colors:")
print(color.RED)
print(" repr:")
print(repr(color.RED))
print(" name:")
print(color.RED.name)
print(" value:")
print(color.RED.value)
print(" GREEN name:")
print(color.GREEN.name)
print(" GREEN value:")
print(color.GREEN.value)
print(" BLUE name:")
print(color.BLUE.name)
print(" BLUE value:")
print(color.BLUE.value)
if color.RED.name=="RED":
  print("yes")
if color.RED.value==1:
  print("yes")
if color.RED==color.GREEN:
  print("Colors are the same")
else:
  print("Colors are different")

Colors:
color.RED
 repr:
<color.RED: 1>
 name:
RED
 value:
1
 GREEN name:
GREEN
 GREEN value:
2
 BLUE name:
BLUE
 BLUE value:
3
yes
yes
Colors are different


In [18]:

class DrawOptions(Enum):
    Axes = 1
    Cube = 2


def drawAxes(img, corner, imgpts):
    corner = tuple(corner[0].ravel().astype(int))
    imgpts = imgpts.reshape(-1, 2).astype(int)
    img = cv2.line(img, corner, tuple(imgpts[0]), (255, 0, 0), 5)
    img = cv2.line(img, corner, tuple(imgpts[1]), (0, 255, 0), 5)
    img = cv2.line(img, corner, tuple(imgpts[2]), (0, 0, 255), 5)
    return img


def drawCube(img, imgpts):
    imgpts = np.int32(imgpts).reshape(-1, 2)
    img = cv2.drawContours(img, [imgpts[:4]], -1, (0, 255, 0), -3)

    for i, j in zip(range(4), range(4, 8)):
        img = cv2.line(img, tuple(imgpts[i]), tuple(imgpts[j]), (255, 255, 255), 3)

    img = cv2.drawContours(img, [imgpts[4:]], -1, (0, 0, 255), 3)
    return img


def PoseEstimations(option: DrawOptions):
    root = os.getcwd()
    path_params = os.path.join(root, "Calibration", "Parameters.npz")

    if not os.path.exists(path_params):
        raise FileNotFoundError(f"Calibration file not found: {path_params}")

    data = np.load(path_params)
    mtx = data["camMatrix"]
    dist = data["distCoef"]

    images = os.path.join(root, "CHESS_IMG", "*.jpg")
    list_img = glob.glob(images)

    if not list_img:
        raise FileNotFoundError(f"No calibration images found in: CHESS_IMG")

    rows = 7
    cols = 7

    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

    pict = np.zeros((rows * cols, 3), np.float32)
    pict[:, :2] = np.mgrid[0:rows, 0:cols].T.reshape(-1, 2)

    axis = np.float32([[3, 0, 0], [0, 3, 0], [0, 0, -3]])

    cubes = np.float32([[1, 1, -1], [1, -1, -1], [-1, -1, -1], [-1, 1, -1],
                        [1, 1, 1], [1, -1, 1], [-1, -1, 1], [-1, 1, 1]])

    for fname in list_img:
        imgBGR = cv2.imread(fname)

        if imgBGR is None:
            continue

        img_gray = cv2.cvtColor(imgBGR, cv2.COLOR_BGR2GRAY)
        ret, corners = cv2.findChessboardCorners(img_gray, (rows, cols), None)

        if not ret:
            continue

        corners2 = cv2.cornerSubPix(img_gray, corners, (11, 11), (-1, -1), criteria)

        ret, rvec, tvec = cv2.solvePnP(pict, corners2, mtx, dist)

        if not ret:
            continue

        if option == DrawOptions.Axes:
            imgpts, _ = cv2.projectPoints(axis, rvec, tvec, mtx, dist)
            imgBGR = drawAxes(imgBGR, corners2, imgpts)

        elif option == DrawOptions.Cube:
            imgpts, _ = cv2.projectPoints(cubes, rvec, tvec, mtx, dist)
            imgBGR = drawCube(imgBGR, imgpts)

        cv2.imshow("Pose Estimation", imgBGR)

        if cv2.waitKey(100) & 0xFF == ord("q"):
            break

    cv2.destroyAllWindows()




In [19]:
if __name__ == "__main__":
    PoseEstimations(DrawOptions.Axes)



In [20]:
if __name__ == "__main__":
    PoseEstimations(DrawOptions.Cube)



# Real Time PoseEstimation

In [5]:

import cv2
import numpy as np
import os
from enum import Enum


# ============================================================
# CONFIGURATION
# ============================================================

Calibration = "Calibration"

CAMERA_ID = 1
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
FPS = 30

ROWS = 7
COLS = 7

AXIS_LENGTH = 3
CUBE_SIZE = 2

WINDOW_NAME = "Professional Pose Estimation"


# ============================================================
# DRAW OPTIONS
# ============================================================

class DrawOptions(Enum):
    Axes = 1
    Cube = 2


# ============================================================
# DRAW PROFESSIONAL AXES
# ============================================================

def drawAxes(img, corner, imgpts):

    corner = tuple(corner[0].ravel().astype(int))
    imgpts = imgpts.reshape(-1, 2).astype(int)

    x_axis = tuple(imgpts[0])
    y_axis = tuple(imgpts[1])
    z_axis = tuple(imgpts[2])

    cv2.arrowedLine(img, corner, x_axis, (0, 0, 255), 5, tipLength=0.15)
    cv2.arrowedLine(img, corner, y_axis, (0, 255, 0), 5, tipLength=0.15)
    cv2.arrowedLine(img, corner, z_axis, (255, 0, 0), 5, tipLength=0.15)

    cv2.putText(img, "X", x_axis, cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 0, 255), 2)
    cv2.putText(img, "Y", y_axis, cv2.FONT_HERSHEY_SIMPLEX, 0.8, (0, 255, 0), 2)
    cv2.putText(img, "Z", z_axis, cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255, 0, 0), 2)

    cv2.circle(img, corner, 7, (255, 255, 255), -1)

    return img


# ============================================================
# DRAW PROFESSIONAL CUBE
# ============================================================

def drawCube(img, imgpts):

    imgpts = np.int32(imgpts).reshape(-1, 2)

    # Cube faces

    cv2.drawContours(img, [imgpts[:4]], -1, (0, 255, 255), 2)
    cv2.drawContours(img, [imgpts[4:]], -1, (255, 0, 255), 2)

    # Cube edges

    for i, j in zip(range(4), range(4, 8)):
        cv2.line(img, tuple(imgpts[i]), tuple(imgpts[j]), (255, 255, 255), 3)

    # Front face

    cv2.polylines(
        img,
        [imgpts[:4]],
        True,
        (0, 255, 0),
        3
    )

    # Back face

    cv2.polylines(
        img,
        [imgpts[4:]],
        True,
        (0, 0, 255),
        3
    )

    # Corner points

    for point in imgpts:
        cv2.circle(img, tuple(point), 4, (255, 255, 255), -1)

    return img


# ============================================================
# DRAW POSE INFORMATION
# ============================================================

def drawPoseInfo(img, tvec):

    x = tvec[0][0]
    y = tvec[1][0]
    z = tvec[2][0]

    cv2.rectangle(img, (20, 20), (300, 135), (30, 30, 30), -1)

    cv2.putText(
        img,
        "POSE ESTIMATION",
        (35, 50),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.65,
        (255, 255, 255),
        2
    )

    cv2.putText(
        img,
        f"X: {x:.2f}",
        (35, 78),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.55,
        (0, 0, 255),
        2
    )

    cv2.putText(
        img,
        f"Y: {y:.2f}",
        (35, 102),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.55,
        (0, 255, 0),
        2
    )

    cv2.putText(
        img,
        f"Z: {z:.2f}",
        (160, 102),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.55,
        (255, 0, 0),
        2
    )

    return img


# ============================================================
# POSE ESTIMATION
# ============================================================

def PoseEstimations(option: DrawOptions):

    root = os.getcwd()

    path_params = os.path.join(
        root,
        Calibration,
        "Parameters.npz"
    )

    if not os.path.exists(path_params):
        raise FileNotFoundError(
            f"Calibration file not found:\n{path_params}"
        )

    data = np.load(path_params)

    mtx = data["camMatrix"]
    dist = data["distCoef"]

    # --------------------------------------------------------
    # Chessboard 3D points
    # --------------------------------------------------------

    pict = np.zeros(
        (ROWS * COLS, 3),
        np.float32
    )

    pict[:, :2] = np.mgrid[
        0:ROWS,
        0:COLS
    ].T.reshape(-1, 2)

    # --------------------------------------------------------
    # Sub-pixel refinement criteria
    # --------------------------------------------------------

    criteria = (
        cv2.TERM_CRITERIA_EPS +
        cv2.TERM_CRITERIA_MAX_ITER,
        30,
        0.001
    )

    # --------------------------------------------------------
    # 3D Axis
    # --------------------------------------------------------

    axis = np.float32([
        [AXIS_LENGTH, 0, 0],
        [0, AXIS_LENGTH, 0],
        [0, 0, -AXIS_LENGTH]
    ])

    # --------------------------------------------------------
    # 3D Cube
    # --------------------------------------------------------

    s = CUBE_SIZE

    cubes = np.float32([
        [s, s, -s],
        [s, -s, -s],
        [-s, -s, -s],
        [-s, s, -s],

        [s, s, s],
        [s, -s, s],
        [-s, -s, s],
        [-s, s, s]
    ])

    # ========================================================
    # CAMERA
    # ========================================================

    cap = cv2.VideoCapture(CAMERA_ID)

    cap.set(
        cv2.CAP_PROP_FRAME_WIDTH,
        FRAME_WIDTH
    )

    cap.set(
        cv2.CAP_PROP_FRAME_HEIGHT,
        FRAME_HEIGHT
    )

    cap.set(
        cv2.CAP_PROP_FPS,
        FPS
    )

    if not cap.isOpened():
        raise RuntimeError("Could not open webcam")

    # ========================================================
    # REAL-TIME LOOP
    # ========================================================

    while True:

        ret, imgBGR = cap.read()
        imgBGR = cv2.rotate(imgBGR, cv2.ROTATE_90_CLOCKWISE)

        if not ret:
            print("Failed to read frame")
            break

        img_gray = cv2.cvtColor(
            imgBGR,
            cv2.COLOR_BGR2GRAY
        )

        # ----------------------------------------------------
        # Detect Chessboard
        # ----------------------------------------------------

        ret, corners = cv2.findChessboardCorners(
            img_gray,
            (ROWS, COLS),
            None
        )

        # ----------------------------------------------------
        # Pose Estimation
        # ----------------------------------------------------

        if ret:

            corners2 = cv2.cornerSubPix(
                img_gray,
                corners,
                (11, 11),
                (-1, -1),
                criteria
            )

            ret, rvec, tvec = cv2.solvePnP(
                pict,
                corners2,
                mtx,
                dist
            )

            if ret:

                # Draw chessboard

                cv2.drawChessboardCorners(
                    imgBGR,
                    (ROWS, COLS),
                    corners2,
                    ret
                )

                # ------------------------------------------------
                # Draw Axes
                # ------------------------------------------------

                if option == DrawOptions.Axes:

                    imgpts, _ = cv2.projectPoints(
                        axis,
                        rvec,
                        tvec,
                        mtx,
                        dist
                    )

                    imgBGR = drawAxes(
                        imgBGR,
                        corners2,
                        imgpts
                    )

                # ------------------------------------------------
                # Draw Cube
                # ------------------------------------------------

                elif option == DrawOptions.Cube:

                    imgpts, _ = cv2.projectPoints(
                        cubes,
                        rvec,
                        tvec,
                        mtx,
                        dist
                    )

                    imgBGR = drawCube(
                        imgBGR,
                        imgpts
                    )

                # ------------------------------------------------
                # Pose Information
                # ------------------------------------------------

                imgBGR = drawPoseInfo(
                    imgBGR,
                    tvec
                )

        # ====================================================
        # STATUS
        # ====================================================

        if ret:
            status = "TRACKING"
            status_color = (0, 255, 0)
        else:
            status = "SEARCHING..."
            status_color = (0, 165, 255)

        cv2.putText(
            imgBGR,
            status,
            (FRAME_WIDTH - 220, 45),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.7,
            status_color,
            2
        )

        # ====================================================
        # DISPLAY
        # ====================================================

        cv2.imshow(
            WINDOW_NAME,
            imgBGR
        )

        # Press Q to exit

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

    # ========================================================
    # RELEASE
    # ========================================================

    cap.release()
    cv2.destroyAllWindows()


# ============================================================
# MAIN
# ============================================================



In [ ]:

if __name__ == "__main__":
    PoseEstimations(DrawOptions.Axes)

In [6]:
if __name__ == "__main__":
    PoseEstimations(DrawOptions.Cube)

# Camera calibration + save parameters

In [14]:
import numpy as np
import cv2 as cv
import glob
import os
import matplotlib.pyplot as plt


def calibrate(showPics=True):

    # Read Images
    root=os.getcwd()
    calibrationDir=os.path.join(root,"CHESS_IMG")
    imgPathList=glob.glob(os.path.join(calibrationDir,"*.jpg"))

    # Initialize
    nRows=7
    nCols=7
    squareSize=20

    termCriteria=(cv.TERM_CRITERIA_EPS+cv.TERM_CRITERIA_MAX_ITER,30,0.001)

    worldPtsCur=np.zeros((nRows*nCols,3),np.float32)
    worldPtsCur[:,:2]=np.mgrid[0:nRows,0:nCols].T.reshape(-1,2)
    worldPtsCur*=squareSize

    worldPtsList=[]
    imgPtsList=[]

    print("Number of images:",len(imgPathList))

    # Find Corners
    for curImgPath in imgPathList:

        imgBGR=cv.imread(curImgPath)

        if imgBGR is None:
            print("Could not read:",curImgPath)
            continue

        imgGray=cv.cvtColor(imgBGR,cv.COLOR_BGR2GRAY)

        cornersFound,cornersOrg=cv.findChessboardCorners(imgGray,(nRows,nCols),None)

        if cornersFound:

            worldPtsList.append(worldPtsCur)

            cornersRefined=cv.cornerSubPix(
                imgGray,
                cornersOrg,
                (11,11),
                (-1,-1),
                termCriteria
            )

            imgPtsList.append(cornersRefined)

            if showPics:
                cv.drawChessboardCorners(
                    imgBGR,
                    (nRows,nCols),
                    cornersRefined,
                    cornersFound
                )

                cv.imshow("Chessboard",imgBGR)

                if cv.waitKey(500)&0xFF==ord("q"):
                    break

        else:
            print("Chessboard not found:",curImgPath)

    cv.destroyAllWindows()

    print("Successful detections:",len(imgPtsList))

    if len(imgPtsList)==0:
        print("No chessboard corners detected.")
        return None,None

    # Calibrate
    repError,camMatrix,distCoeff,rvecs,tvecs=cv.calibrateCamera(
        worldPtsList,
        imgPtsList,
        imgGray.shape[::-1],
        None,
        None
    )

    print("Camera Matrix:\n",camMatrix)
    print("Distortion Coefficients:\n",distCoeff)
    print("Reproj Error (pixels): {:.4f}".format(repError))

    # Save Calibration Parameters
    folderCalibration="Calibration"

    if not os.path.exists(folderCalibration):
        os.makedirs(folderCalibration)

    paramPath=os.path.join(folderCalibration,"Parameters.npz")

    np.savez(
        paramPath,
        repError=repError,
        camMatrix=camMatrix,
        distCoeff=distCoeff,
        rvecs=rvecs,
        tvecs=tvecs
    )

    print("Calibration parameters saved successfully.")

    return camMatrix,distCoeff


def removeDistortion(camMatrix,distCoeff):

    root=os.getcwd()

    imgPath=os.path.join(root,"a.jpg")

    img=cv.imread(imgPath)

    if img is None:
        print("Could not read a.jpg")
        return

    height,width=img.shape[:2]

    camMatrixNew,roi=cv.getOptimalNewCameraMatrix(
        camMatrix,
        distCoeff,
        (width,height),
        1,
        (width,height)
    )

    print("New Camera Matrix:\n",camMatrixNew)

    imgUndist=cv.undistort(
        img,
        camMatrix,
        distCoeff,
        None,
        camMatrixNew
    )

    x,y,w,h=roi

    imgUndistCropped=imgUndist[y:y+h,x:x+w]

    # Draw Line To See Distortion Change
    cv.line(img,(1769,103),(1780,922),(255,255,255),2)
    cv.line(imgUndist,(1769,103),(1780,922),(255,255,255),2)

    plt.figure()

    plt.subplot(121)
    plt.imshow(cv.cvtColor(img,cv.COLOR_BGR2RGB))
    plt.title("Original")

    plt.subplot(122)
    plt.imshow(cv.cvtColor(imgUndistCropped,cv.COLOR_BGR2RGB))
    plt.title("Undistorted")

    plt.show()


def runCalibration():

    calibrate(showPics=True)


def runRemoveDistortion():

    camMatrix,distCoeff=calibrate(showPics=False)

    if camMatrix is not None:
        removeDistortion(camMatrix,distCoeff)


if __name__=="__main__":

    # runCalibration()
    runRemoveDistortion()

Number of images: 10
Chessboard not found: D:\proj-python\Images_Vision\CHESS_IMG\image_10.jpg
Chessboard not found: D:\proj-python\Images_Vision\CHESS_IMG\image_4.jpg
Chessboard not found: D:\proj-python\Images_Vision\CHESS_IMG\image_7.jpg
Chessboard not found: D:\proj-python\Images_Vision\CHESS_IMG\image_9.jpg
Successful detections: 6
Camera Matrix:
 [[1.59973663e+03 0.00000000e+00 5.39770260e+02]
 [0.00000000e+00 1.56842636e+03 8.89616180e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Coefficients:
 [[-1.08799416e-01  7.77557942e-01  8.99357266e-04  2.86628405e-02
  -1.12488534e+00]]
Reproj Error (pixels): 1.2252
Calibration parameters saved successfully.
Could not read a.jpg


# Pose estimation — AXES / CUBE

In [16]:
import numpy as np
import cv2 as cv
import glob
import os
from enum import Enum


class DrawOption(Enum):

    AXES=1
    CUBE=2


def drawAxes(img,corners,imgpts):

    def tupleOfInts(arr):
        return tuple(int(x) for x in arr)

    corner=tupleOfInts(corners[0].ravel())

    img=cv.line(
        img,
        corner,
        tupleOfInts(imgpts[0].ravel()),
        (255,0,0),
        5
    )

    img=cv.line(
        img,
        corner,
        tupleOfInts(imgpts[1].ravel()),
        (0,255,0),
        5
    )

    img=cv.line(
        img,
        corner,
        tupleOfInts(imgpts[2].ravel()),
        (0,0,255),
        5
    )

    return img


def drawCube(img,imgpts):

    imgpts=np.int32(imgpts).reshape(-1,2)

    # Add green plane
    img=cv.drawContours(
        img,
        [imgpts[:4]],
        -1,
        (0,255,0),
        -3
    )

    # Add box borders
    for i in range(4):

        j=i+4

        img=cv.line(
            img,
            tuple(imgpts[i]),
            tuple(imgpts[j]),
            (255,255,255),
            3
        )

    img=cv.drawContours(
        img,
        [imgpts[4:]],
        -1,
        (0,0,255),
        3
    )

    return img


def poseEstimation(option:DrawOption):

    # Retrieve calibration parameters
    root=os.getcwd()

    paramPath=os.path.join(
        root,
        "Calibration",
        "Parameters.npz"
    )

    data=np.load(paramPath)

    camMatrix=data["camMatrix"]
    distCoeff=data["distCoeff"]

    print("Camera Matrix:")
    print(camMatrix)

    print("Distortion Coefficients:")
    print(distCoeff)

    # Obtain image paths
    calibrationDir=os.path.join(root,"CHESS_IMG")

    imgPathList=glob.glob(
        os.path.join(calibrationDir,"*.jpg")
    )

    # Initialize
    nRows=7
    nCols=7
    squareSize=20

    termCriteria=(
        cv.TERM_CRITERIA_EPS+
        cv.TERM_CRITERIA_MAX_ITER,
        30,
        0.001
    )

    worldPtsCur=np.zeros(
        (nRows*nCols,3),
        np.float32
    )

    worldPtsCur[:,:2]=np.mgrid[
        0:nRows,
        0:nCols
    ].T.reshape(-1,2)

    worldPtsCur*=squareSize

    # World points of objects to be drawn
    axis=np.float32([
        [3,0,0],
        [0,3,0],
        [0,0,-3]
    ])

    cubeCorners=np.float32([
        [0,0,0],
        [0,3,0],
        [3,3,0],
        [3,0,0],

        [0,0,-3],
        [0,3,-3],
        [3,3,-3],
        [3,0,-3]
    ])

    # Find corners
    for curImgPath in imgPathList:

        imgBGR=cv.imread(curImgPath)

        if imgBGR is None:
            continue

        imgGray=cv.cvtColor(
            imgBGR,
            cv.COLOR_BGR2GRAY
        )

        cornersFound,cornersOrg=cv.findChessboardCorners(
            imgGray,
            (nRows,nCols),
            None
        )

        if cornersFound:

            cornersRefined=cv.cornerSubPix(
                imgGray,
                cornersOrg,
                (11,11),
                (-1,-1),
                termCriteria
            )

            success,rvec,tvec=cv.solvePnP(
                worldPtsCur,
                cornersRefined,
                camMatrix,
                distCoeff
            )

            if not success:
                continue

            if option==DrawOption.AXES:

                imgpts,_=cv.projectPoints(
                    axis,
                    rvec,
                    tvec,
                    camMatrix,
                    distCoeff
                )

                print("imgpts:")
                print(imgpts)

                imgBGR=drawAxes(
                    imgBGR,
                    cornersRefined,
                    imgpts
                )

            if option==DrawOption.CUBE:

                imgpts,_=cv.projectPoints(
                    cubeCorners,
                    rvec,
                    tvec,
                    camMatrix,
                    distCoeff
                )

                imgBGR=drawCube(
                    imgBGR,
                    imgpts
                )

            cv.imshow("Chessboard",imgBGR)

            if cv.waitKey(5000)&0xFF==ord("q"):
                break

    cv.destroyAllWindows()


if __name__=="__main__":

    # poseEstimation(DrawOption.AXES)

    poseEstimation(DrawOption.CUBE)

Camera Matrix:
[[1.59973663e+03 0.00000000e+00 5.39770260e+02]
 [0.00000000e+00 1.56842636e+03 8.89616180e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Coefficients:
[[-1.08799416e-01  7.77557942e-01  8.99357266e-04  2.86628405e-02
  -1.12488534e+00]]


In [18]:

import numpy as np
import cv2 as cv
import os

# Load Calibration Parameters
root=os.getcwd()
paramPath=os.path.join(root,"Calibration","Parameters.npz")

data=np.load(paramPath)

camMatrix=data["camMatrix"]
distCoeff=data["distCoeff"]

print("Camera Matrix:")
print(camMatrix)

print("Distortion Coefficients:")
print(distCoeff)

# Start Camera
cap=cv.VideoCapture(1)

if not cap.isOpened():
    print("Could not open camera")
    exit()

# Get Camera Resolution
width=int(cap.get(cv.CAP_PROP_FRAME_WIDTH))
height=int(cap.get(cv.CAP_PROP_FRAME_HEIGHT))

print("Camera Resolution:",width,"x",height)

# Optimize Camera Matrix
camMatrixNew,roi=cv.getOptimalNewCameraMatrix(
    camMatrix,
    distCoeff,
    (width,height),
    1,
    (width,height)
)

print("New Camera Matrix:")
print(camMatrixNew)

while True:

    ret,frame=cap.read()
    frame=cv2.rotate(frame,cv2.ROTATE_90_CLOCKWISE)

    if not ret:
        break

    # Undistort Frame
    frameUndist=cv.undistort(
        frame,
        camMatrix,
        distCoeff,
        None,
        camMatrixNew
    )

    # Crop Undistorted Frame
    x,y,w,h=roi
    frameUndistCropped=frameUndist[y:y+h,x:x+w]

    # Display
    cv.imshow("Original",frame)
    cv.imshow("Undistorted",frameUndistCropped)

    if cv.waitKey(1)&0xFF==ord("q"):
        break

cap.release()
cv.destroyAllWindows()


Camera Matrix:
[[1.59973663e+03 0.00000000e+00 5.39770260e+02]
 [0.00000000e+00 1.56842636e+03 8.89616180e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Coefficients:
[[-1.08799416e-01  7.77557942e-01  8.99357266e-04  2.86628405e-02
  -1.12488534e+00]]
Camera Resolution: 640 x 480
New Camera Matrix:
[[1.53416674e+03 0.00000000e+00 5.46903151e+02]
 [0.00000000e+00 1.52091514e+03 8.77778241e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
