In [5]:
import numpy as np
import cv2
import os
os.chdir(r"D:\proj-python\Images_Vision")
img=cv2.imread("king_and_queen.jpg")
width,height=300,400
pts1=np.float32([[25,25],[215,27],[25,310],[215,310]])
pts2=np.float32([[0,0],[width,0],[0,height],[width,height]])
matrix=cv2.getPerspectiveTransform(pts1,pts2)
imgOutput=cv2.warpPerspective(img,matrix,(width,height))
print(imgOutput)
print(imgOutput.shape)
for i in range(4):
  cv2.circle(img,(int(pts1[i][0]),int(pts1[i][1])),5,(0,0,255),cv2.FILLED)
cv2.imshow("Image",img)
cv2.imshow("Output",imgOutput)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[232 249 255]
  [234 248 255]
  [235 247 255]
  ...
  [252 255 251]
  [251 255 253]
  [232 239 239]]

 [[249 252 253]
  [249 253 254]
  [249 252 254]
  ...
  [249 254 253]
  [246 255 254]
  [225 236 237]]

 [[246 253 249]
  [248 254 250]
  [249 254 250]
  ...
  [246 254 254]
  [243 255 255]
  [220 234 235]]

 ...

 [[247 251 252]
  [247 252 252]
  [247 251 250]
  ...
  [252 254 255]
  [249 254 255]
  [212 219 222]]

 [[247 252 253]
  [247 253 253]
  [248 253 253]
  ...
  [245 247 249]
  [243 248 251]
  [207 214 218]]

 [[247 253 255]
  [247 254 255]
  [247 254 255]
  ...
  [242 243 247]
  [241 246 250]
  [208 215 219]]]
(400, 300, 3)
